spring:
  application:
    name: gym-crm

  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: gym
    password: gym
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog-master.xml

server:
  port: 8080

app:
  api:
    base-path: /api/v1

password:
  length: 10
  characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%"