storage.init.file=classpath:data/storage-init.csv

password.length=10
password.characters=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/gym
db.username=gym
db.password=gym
